#
#Makefile for VIRGO queue 
#

ccflags-y := -w -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.10.3/lib -I-I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.10.3/include -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.10.3/include -DDEBUG

kingcobra_main_kernelspace_driver-y	+= kingcobra_main_kernelspace.o
obj-m               += kingcobra_main_kernelspace.o
